src/PaulStudios/urls.py
from django.contrib import admin
from django.core.exceptions import PermissionDenied
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler500, handler403, handler404

    
handler404 = "base.views.custom_404"
handler403 = "base.views.custom_403"
handler500 = "base.views.custom_500"


urlpatterns = [
    path('', TemplateView.as_view(template_name='profiles/index.html'),
        name='home'),
    path('admin/', admin.site.urls),
    path('profiles/', include("profiles.urls")),
    path('backend/', include("base.urls")),
    path('jarvisai/', include("jarvisai.urls")),
    path('song-downloader/', include("songdownloader.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
]

  
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/base/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

app_name = "backend"

urlpatterns = [
    path("task-progress/<str:task_id>", views.task_progress, name="task_progress")
]

src/jarvisai/urls.py
from django.urls import path

from . import views

app_name = "jarvisai"

urlpatterns = [
    path("chat", views.chat_view, name="chat"),
    path("chat/bot_response", views.bot_response, name="bot_response"),
    path('chat/history', views.chat_history, name='chat_history'),
    path('chat/history/<int:chat_id>', views.chat_detail, name='chat_detail'),
]

src/profiles/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

app_name = "profiles"
urlpatterns = [
    path("", views.index, name="index"),
    path("info/", views.detail, name="info"),
    path('send-activation-mail', views.send_activation_mail, name="send-activation-mail"),
    path('activate/<str:code>/', views.activate_user_view, name='activate'),
    path('login/', LoginView.as_view(template_name='profiles/login.html', redirect_authenticated_user=True), name='login'),
    path('login_otp/<str:page_type>/<str:code>/', views.login_otp, name='login_otp'),
    path('error/<str:type>', views.error_page, name="error_page"),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.Register, name='register'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('reset_password/<uidb64>/<token>/', views.password_reset_action, name='reset_password_action'),
]

src/songdownloader/urls.py
from django.urls import path, include
from . import views

app_name = 'songdownloader'

urlpatterns = [
    path('', views.index, name='index'),
    path("<str:task_id>", views.show_progress, name='progress'),
    path("<str:task_id>/download", views.download_file, name='download'),
]

src/profiles/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

from profiles.models import UserProfile

user = UserProfile


class RegistrationForm(UserCreationForm):
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'id': 'password-input'}),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput()
    )
    password_strength = forms.CharField(
        widget=forms.HiddenInput(),
        required=False,
    )
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column('first_name', css_class='form-group col-md-6 mb-0'),
                Column('last_name', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('username', css_class='form-group col-md-3 mb-0'),
                Column('email', css_class='form-group col-md-5 mb-0'),
                Column('country', css_class='form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
            Row(
                Column('password1', css_class='form-group col-md-6 mb-0'),
                Column('password2', css_class='form-group col-md-6 mb-0'),
                css_class='form-row'
            ),
            Row(Column('captcha', css_class='form-group col-md-4 mb-0 bg-transparent'), css_class='form-row'),
            Submit('submit', 'Register')
        )

    class Meta:
        model = user
        fields = ["first_name", "last_name",
                  "username",
                  "email", "country", ]


class OTPLoginForm(forms.Form):
    input_data = forms.CharField(label="Username/ Email")


class EnterOTPForm(forms.Form):
    code = forms.CharField(
        max_length=6,
        label='Enter your verification code',
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '6-digit code'
        })
    )

src/base/views.py
import redis
from celery.result import AsyncResult
from django.http import JsonResponse
from django.shortcuts import render

from PaulStudios import settings

redis_db = redis.from_url(settings.REDIS_URL, decode_responses=True)


def task_progress(request, task_id):
    result = AsyncResult(task_id)
    try:
        response_data = {
            'progress': redis_db.get(f"progress-{task_id}"),
            'total': redis_db.get(f"total-{task_id}"),
            'image': redis_db.get(f"image-{task_id}"),
            'current': redis_db.get(f"current-{task_id}"),
            'name': redis_db.get(f"name-{task_id}"),
            'state': result.state,
            'details': result.info,
        }
        return JsonResponse(response_data)
    except Exception as e:
        print(e)
        return JsonResponse({'error': str(e)})


def custom_403(request, exception):
    return render(request, 'base/403.html', status=403)


def custom_404(request, exception):
    return render(request, 'base/404.html', status=404)


def custom_500(request):
    return render(request, 'base/500.html', status=500)

src/profiles/views.py
import redis
from django.contrib import messages
from django.contrib.auth import logout, get_user_model, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.hashers import check_password
from django.core.cache import cache
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

from PaulStudios import settings
from .forms import RegistrationForm, OTPLoginForm, EnterOTPForm
from .models import PasswordsProfile
from .tasks import send_activation_email, send_reset_password_email, send_login_email
from .utilities import is_base64, validateEmail

PRIVATE_IPS_PREFIX = ('10.', '172.', '192.', '127.')
redis_db = redis.from_url(settings.REDIS_URL, decode_responses=True)
User = get_user_model()


def get_client_ip(request):
    """get the client ip from the request
    """
    remote_address = request.META.get('REMOTE_ADDR')
    # set the default value of the ip to be the REMOTE_ADDR if available
    # else None
    ip = remote_address
    # try to get the first non-proxy ip (not a private ip) from the
    # HTTP_X_FORWARDED_FOR
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        proxies = x_forwarded_for.split(',')
        # remove the private ips from the beginning
        while (len(proxies) > 0 and
               proxies[0].startswith(PRIVATE_IPS_PREFIX)):
            proxies.pop(0)
        # take the first ip which is not a private one (of a proxy)
        if len(proxies) > 0:
            ip = proxies[0]

    return ip


def user_check(request):
    user = request.user
    if not user.is_authenticated:
        messages.error(request, 'You are not logged in.', extra_tags="danger")
        return redirect(f"{settings.LOGIN_URL}?next={request.path}")
    if not user.activated:
        messages.error(request, 'Your account is not activated. Please verify your mail first!', extra_tags="danger")
        return redirect(reverse("profiles:error_page", kwargs={'type': "mail_verify"}))
    return


def index(request):
    return render(request, 'profiles/index.html', {})


@login_required
def detail(request):
    return render(request, 'profiles/info.html')


@login_required
def user_logout(request):
    logout(request)
    return render(request, 'profiles/logged_out.html', {})


def Register(request):
    if request.method == 'POST':
        # Create a form that has request.POST
        form = RegistrationForm(request.POST)
        print(form.errors)
        if form.is_valid():
            user = form.save(commit=False)
            # Set the user's password securely
            password = form.cleaned_data['password2']
            password1 = form.cleaned_data['password1']

            if password == password1:
                user.set_password(password)
                user.register_ip = get_client_ip(request)

                user.save()
                messages.success(request, "User registered. Please activate your profile by verifying your email.")
                return redirect(
                    reverse("profiles:error_page", kwargs={'type': 'mail_verify'}))  # Redirect to the login page
            else:
                # Handle password mismatch error here
                form.add_error('password2', 'Passwords entered do not match')
        else:
            for key, error in list(form.errors.items()):
                if key == 'captcha' and error[0] == 'This field is required.':
                    messages.error(request, "You must pass the reCAPTCHA test", extra_tags="danger")
                    continue
                messages.error(request, error)
    else:
        form = RegistrationForm()
    return render(request, 'profiles/register.html', {'form': form})


@login_required
def error_page(request, *args, type=None, **kwargs):
    if type == "mail_verify":
        return render(request, 'profiles/errors/mail_verify.html')


def send_activation_mail(request):
    send_activation_email.delay(request.scheme, request.get_host(), request.user.id)
    messages.info(request, "Mail has been sent")
    if not PasswordsProfile.objects.filter(user=request.user).exists():
        profile = PasswordsProfile.objects.create(user=request.user)
        profile.old_passwords.append(request.user.password)
        profile.save()
    return redirect(reverse("profiles:info"))


def activate_user_view(request, *args, code=None, **kwargs):
    if code:
        if not is_base64(code):
            messages.error(request, "Your activation key is invalid.", extra_tags="danger")
            return redirect(reverse("profiles:login"))
        code = urlsafe_base64_decode(code).decode('utf-8')
        qs = User.objects.filter(activation_key=code)
        if qs.exists() and qs.count() == 1:
            profile = qs.first()
            if not redis_db.exists(profile.activation_key):
                messages.error(request, 'Your activation key has expired.', extra_tags="danger")
                return redirect(reverse("profiles:login"))
            if not profile.activated:
                profile.activated = True
                profile.activation_key = "DONE"
                profile.save()
                messages.success(request, "Profile activated. You now have complete access to all Apps & Services.")
                return redirect(reverse("profiles:login"))
            messages.success(request, "Profile already activated.")
            return redirect(reverse("profiles:info"))
        messages.error(request, "Your activation key is invalid.", extra_tags="danger")
        return redirect(reverse("profiles:login"))
    return redirect(reverse("profiles:info"))


def reset_password(request, *args, **kwargs):
    if request.method == "POST":
        form = PasswordResetForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data['email']
            user = User.objects.filter(email=data)
            if user.exists():
                send_reset_password_email.delay(request.scheme, request.get_host(), user.first().id)
            messages.success(request, "If this email is associated with an account, a mail will be sent with "
                                      "instructions on how to reset your password.")
            return redirect(reverse("profiles:login"))
    else:
        form = PasswordResetForm()
    return render(request, "profiles/reset/reset.html", {"form": form})


def password_reset_action(request, uidb64=None, token=None):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = get_object_or_404(User, pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == "POST":
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save(commit=False)
                newpassword = form.cleaned_data['new_password1']
                try:
                    # Retrieve the PasswordsProfile instance for the user
                    profile = PasswordsProfile.objects.get(user=user)
                except PasswordsProfile.DoesNotExist:
                    profile = PasswordsProfile.objects.create(user=user)
                    profile.old_passwords.append(user.password)
                    profile.save()
                    # Check if the entered password matches any of the previous passwords
                if not isinstance(profile.old_passwords, list):
                    profile.previous_passwords = []
                for old_password in profile.old_passwords:
                    if check_password(newpassword, old_password):
                        exists = True
                    else:
                        exists = False
                if exists:
                    messages.error(request, "You cannot use a previously used password.", extra_tags="danger")
                    return render(request, 'profiles/reset/confirm.html', {'form': form, 'validlink': True})
                else:
                    profile = PasswordsProfile.objects.get(user=user)
                    profile.old_passwords.append(user.password)
                    profile.save()
                    form.save()
                    messages.success(request, "Your password has been reset. Please login again.")
                return redirect(reverse("profiles:login"))
        else:
            form = SetPasswordForm(user)
        messages.success(request, "Your link is valid. Please set your new password.")
        return render(request, 'profiles/reset/confirm.html', {'form': form, 'validlink': True})
    else:
        messages.error(request, "Invalid Reset link. Link may have expired", extra_tags="danger")
        return render(request, 'profiles/reset/confirm.html', {'validlink': False})


def login_otp(request, page_type=None, code=None):
    if page_type == "1" and code == "step1":
        if request.method == "POST":
            form = OTPLoginForm(request.POST)
            if form.is_valid():
                user_info = form.cleaned_data['input_data']
                if validateEmail(user_info):
                    user = User.objects.filter(email=user_info)
                    user = user.first()
                else:
                    user = User.objects.filter(username=user_info)
                    user = user.first()
                if user is None:
                    messages.error(request, "The account information entered is invalid.", extra_tags="danger")

src/profiles/templates/profiles/activation_email.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account Activation</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: Arial, sans-serif;
        }
        .email-container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #e0e0e0;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            background-color: #ffffff;
        }
        .header {
            text-align: center;
            padding: 10px;
            border-bottom: 1px solid #e0e0e0;
        }
        .header img {
            max-width: 100px;
        }
        .content {
            padding: 20px;
        }
        .footer {
            text-align: center;
            padding: 10px;
            border-top: 1px solid #e0e0e0;
            font-size: 12px;
            color: #777777;
        }
        .btn-primary {
            background-color: #007bff;
            border-color: #007bff;
            color: #ffffff;
            padding: 10px 20px;
            border-radius: 5px;
            text-decoration: none;
            display: inline-block;
        }
    </style>
</head>
<body>
    <div class="email-container">
        <div class="header">
            <img src="{% static 'logo.png' %}" alt="Logo">
            <h1>PaulStudios</h1>
        </div>
        <div class="content">
            <h3>Activate Your Account</h3>
            <p>Hello {{ user.username }},</p>
            <p>Thank you for signing up on our platform. Please click the button below to activate your account:</p>
            <p class="text-light fw-bold"><a href="{{ activation_link }}" class="btn btn-primary">Activate Account</a></p>
            <p>If the button above doesn't work, copy and paste the following link into your browser:</p>
            <p><a href="{{ activation_link }}">{{ activation_link }}</a></p>
        </div>
        <div class="footer">
            <p>&copy; 2024 PaulStudios. All rights reserved.</p>
        </div>
    </div>
</body>
</html>

src/profiles/templates/profiles/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <title>
    {% block title %}
    PaulStudios
    {% endblock title %}
  </title>
  <style>
.asteriskField {
    color: red;
}
</style>
  {% block extra_head %}
  {% endblock extra_head %}
</head>
<body style="height: 100%;
    background-image: url({% static 'profiles/bg.png' %});
    height: 100vh;
    background-repeat: repeat-y;
    background-attachment: fixed;
    background-size: 100% 100%;
    background-position: 0px 30px;
    ">
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark" style="background-color: #123670;">
      &nbsp;&nbsp;&nbsp;
  <a class="navbar-brand" href="{%url 'profiles:index'%}">
    <img src="{% static 'logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
    Paul Studios
  </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'jarvisai:chat'%}" tabindex="-1" aria-disabled="true">JarvisAI</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'songdownloader:index'%}" tabindex="-1" aria-disabled="true">Song-Downloader</a>
      </li>
      </ul>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ms-auto">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'profiles:info'%}">
          <img src="{% static 'profiles/account.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        </a>
      </li>&nbsp;&nbsp;
      <li class="nav-item">
    <a class="nav-link" href="{%url 'profiles:login'%}">
      Login
    </a>
    </li>&nbsp;&nbsp;
      <li class="nav-item">
    <a class="nav-link" href="{%url 'profiles:register'%}">
      Register
    </a>
      </li>&nbsp;&nbsp;&nbsp;&nbsp;
    </ul>
  </div>
</nav>

{% for msg in messages %}
  <div class="alert alert-{{ msg.tags }} alert-dismissible fade show" role="alert">
    {{ msg }}
  </div>
{% endfor %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>
  <div class="container" style="">
    {% block content %}
    {% endblock %}
  </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script type="text/javascript">
    var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
    var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
      return new bootstrap.Tooltip(tooltipTriggerEl)
    })
</script>
</body>
</html>

src/profiles/templates/profiles/index.html
{% extends 'profiles/base.html' %}
{% block content %}
<h1 class="text-primary">Info Page</h1>
<div class="text-light">
  {% if user.is_authenticated %}
    Hello {{ user }}. Welcome to PaulStudios
    <a href="{% url 'profiles:logout' %}">Click here to log out.</a>
  {% else %}
    Hello Anonymous. Welcome to PaulStudios
    You are not logged in.
  <br>
    <a href="{% url 'profiles:login' %}">Click here to log in.</a>
  {% endif %}
</div>
{% endblock %}

src/profiles/templates/profiles/info.html
{% extends 'profiles/base.html' %}
{% block content %}
<h1 class="text-success">Info Page</h1>
<div class="text-light">
    You are logged in as {{ user }}.
    <a href="{% url 'profiles:logout' %}">Click here to log out.</a>
</div>
{% endblock %}

src/profiles/templates/profiles/logged_out.html
{% extends 'profiles/base.html' %}
{% block content %}
<p style="height:220px"></p>
<div class="text-center">
    <div class="alert alert-success" role="alert" id="message_logout">
        <h1 class="alert-heading text-center">Success!</h1>
        You have been successfully logged out! Hope you enjoyed our services.
        <hr>
        <a href="{% url 'profiles:login' %}" class="alert-link"> Click here to log in again.</a>
        <p class="mb-0"></p>
    </div>
</div>
{% endblock %}

src/profiles/templates/profiles/login.html
{% extends 'profiles/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Paul Studios | Login
{% endblock title %}
{% block content %}
  <div class="row">
    <div class="col-md-6 mx-auto">
      <div class="card mt-5" style="background-color: rgba(0, 0, 0, 0);">
        <div class="card-body text-center">
            <img src="{% static 'logo.png' %}"
                             class="img-fluid mb-3"
                             alt="PaulStudios Logo"
                             style="max-width: 150px;">
            <div class="mx-auto d-flex justify-content-center" style="width: 200px;color: skyblue;">
                <h1 class="fw-bold">Login</h1>
            </div>
            <div style="background-color: rgba(0, 0, 0, 0.5);">
                <div class="text-light fw-bold">
                <form method="post" >
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-placement="right" title="Log in to PaulStudios">Sign in</button>
                    {% if mode != 'otp' %}
                    <h6><a href="{%url 'profiles:reset_password'%}" class="text-light">Forgot Password? </a></h6>
                    {% endif %}
                </form>
                </div>
                <h6 class="text-warning">
                    Need An Account? <a href="{%url 'profiles:register'%}" class="card-link">Sign Up</a>
                </h6>
                {% if mode != 'otp' %}
                    <hr>
                    <hr>
                    <h2>OR</h2>
                    <hr>
                    <hr>
                    <div class="text-danger fw-bold">
                        <button class="btn btn-success" data-bs-toggle="tooltip"
                                data-bs-placement="right" title="Login using OTP received by email."
                                onclick="myfunc()">
                       Login using OTP
                    </button></div>
                {% else %}
                    <hr>
                    <hr>
                    <h2>OR</h2>
                    <hr>
                    <hr>
                    <div class="text-danger fw-bold">
                        <button class="btn btn-success" data-bs-toggle="tooltip"
                                data-bs-placement="right" title="Login using Password."
                                onclick="myfunc2()">
                       Login using Password
                    </button></div>
                {% endif %}
            </div>
        </div>
      </div>
    </div>
  </div>
<script>
    function myfunc(){
        location.replace("{%url 'profiles:login_otp' page_type='1' code='step1' %}")
    }
    function myfunc2(){
        location.replace("{%url 'profiles:login' %}")
    }
</script>
{% endblock %}

src/profiles/templates/profiles/register.html
{% extends 'profiles/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
Paul Studios | Register
{% endblock title %}

{% block content %}
<div class="text-center">
    <br>
    <img src="{% static 'logo.png' %}"
                             class="img-fluid mb-3"
                             alt="PaulStudios Logo"
                             style="max-width: 150px;">
            <div class="mx-auto d-flex justify-content-center" style="width: 200px;color: skyblue;">
                <h1 class="fw-bold">Register</h1>
            </div></div>
    <form method="post">
        <div class="text-light fw-bold">
        {% csrf_token %}
        {% crispy form %}
            <div></div>
            <strong>Password Strength:</strong>&nbsp;&nbsp;&nbsp;
            <div id="password-strength" style="display:inline-block">Please enter a password.</div>
        </div>
    </form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/zxcvbn/4.4.2/zxcvbn.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const passwordInput = document.getElementById('password-input');
    const passwordStrengthField = document.getElementById('password-strength');

    passwordInput.addEventListener('input', function () {
        const password = passwordInput.value;
        const result = zxcvbn(password);

        // Update password strength feedback
        passwordStrengthField.innerHTML = ''; // Clear previous feedback

        if (result.score === 0) {
            passwordStrengthField.innerHTML = '<span style="color: red;">Very Weak</span>';
        } else if (result.score === 1) {
            passwordStrengthField.innerHTML = '<span style="color: orange;">Weak</span>';
        } else if (result.score === 2) {
            passwordStrengthField.innerHTML = '<span style="color: yellow;">Medium</span>';
        } else if (result.score === 3) {
            passwordStrengthField.innerHTML = '<span style="color: green;">Strong</span>';
        } else if (result.score === 4) {
            passwordStrengthField.innerHTML = '<span style="color: darkgreen;">Very Strong</span>';
        }
    });
});
</script>
{% endblock %}