src/PaulStudios/urls.py
from django.contrib import admin
from django.core.exceptions import PermissionDenied
from django.urls import path, include
from django.views.generic.base import TemplateView, RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import handler500, handler403, handler404

    
handler404 = "base.views.custom_404"
handler403 = "base.views.custom_403"
handler500 = "base.views.custom_500"


urlpatterns = [
    path('', TemplateView.as_view(template_name='profiles/index.html'),
        name='home'),
    path('admin/', admin.site.urls),
    path('profiles/', include("profiles.urls")),
    path('backend/', include("base.urls")),
    path('jarvisai/', include("jarvisai.urls")),
    path('song-downloader/', include("songdownloader.urls")),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon/favicon.ico'))),
]

  
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/base/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from . import views

app_name = "backend"

urlpatterns = [
    path("task-progress/<str:task_id>", views.task_progress, name="task_progress")
]

src/jarvisai/urls.py
from django.urls import path

from . import views

app_name = "jarvisai"

urlpatterns = [
    path("chat", views.chat_view, name="chat"),
    path("chat/bot_response", views.bot_response, name="bot_response"),
    path('chat/history', views.chat_history, name='chat_history'),
    path('chat/history/<int:chat_id>', views.chat_detail, name='chat_detail'),
]

src/jarvisai/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class ChatMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    response = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username}: {self.message} / {self.response}'

src/jarvisai/forms.py
from django.forms import forms, CharField, Textarea


class ChatForm(forms.Form):
    message = CharField(widget=Textarea, label='Enter your message')

src/jarvisai/views.py
import requests.exceptions
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt

from profiles.views import user_check
from .chatbot import Bot
from .models import ChatMessage

bot = Bot()


@csrf_exempt
def chat_view(request):
    c = user_check(request)
    if c: return c
    user = request.user
    return render(request, 'jarvisai/chat.html', {'username': user.first_name, 'first_name': user.first_name})


@login_required
@csrf_exempt
def bot_response(request):
    if request.method == 'POST':
        message = request.POST.get("msg1", "")
        if message:
            try:
                response = bot.process(message)
            except requests.exceptions.ReadTimeout as e:
                response = "Sorry, PaulStudios Servers are currently down. Please check again after some time."
            ChatMessage.objects.create(
                user=request.user,
                message=message,
                response=response
            )
            # Keep only the last 20 messages per user
            user_chat_logs = ChatMessage.objects.filter(user=request.user).order_by('-timestamp')
            if user_chat_logs.count() > 20:
                user_chat_logs[20:].delete()
            return JsonResponse({'response': response})
        else:
            return JsonResponse({'error': 'Message not provided'}, status=400)
    return JsonResponse({'error': 'Invalid request method'}, status=405)


@login_required
@csrf_exempt
def chat_history(request):
    chats = ChatMessage.objects.filter(user=request.user).order_by('-timestamp')
    chat_list = [{'id': chat.id, 'user_message': chat.message, 'bot_response': chat.response, 'timestamp': chat.timestamp} for chat in chats]
    return JsonResponse(chat_list, safe=False)

@login_required
@csrf_exempt
def chat_detail(request, chat_id):
    chat = get_object_or_404(ChatMessage, id=chat_id, user=request.user)
    messages = [
        {'sender': request.user.first_name, 'message': chat.message},
        {'sender': 'JarvisAI', 'message': chat.response}
    ]
    return JsonResponse({'messages': messages})

src/jarvisai/templates/jarvisai/chat.html
{% extends 'profiles/base.html' %}
{% load static %}

{% block title %}
Paul Studios | JarvisAI
{% endblock title %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'jarvisai/chat.css' %}">
<script src="{% static 'jarvisai/chat.js' %}"></script>
<link rel="stylesheet" href="{% static 'jarvisai/multicolor.css' %}">
<script defer src="{% static 'jarvisai/multicolor.js' %}"></script>
{% endblock extra_head %}

{% block content %}
     <div class="container-fluid" id="chat_container">
        <div id="flashy_heading_container">
            <h1 id="flashy_heading" class="text-center">Chat with JarvisAI</h1>
        </div>
        <div class="row">
            <div class="col-md-8" id="main_content">
                <div id="chat_log" class="chat-box border p-3 mb-3" style="background-color: rgba(0, 0, 0, 0.5);"></div>
                <div id="input_container" class="input-group mb-3">
                    <input type="text" id="message_input" class="form-control" placeholder="Type your message here...">
                    <button data-url="{% url 'jarvisai:bot_response' %}" id="send_button" class="btn btn-primary">Send</button>
                </div>
            </div>
            <div class="col-md-4" id="sidebar">
                <h2>Chat History</h2>
                <div id="chat_history" class="list-group"></div>
            </div>
        </div>
    </div>
    <script>
        const username = "{{ username }}";  // Accessing username from template context
    </script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="{% static 'jarvisai/chat.js' %}"></script>
{% endblock %}